#!/usr/bin/env ruby

require 'rubygems'
require 'thor'

class ThorExample < Thor
  desc "start", "start server"
  option :batches, :type => :hash, :required => true, :aliases => "-b",
         :desc => "which environment you want server run."
  option :partition_file, :required => true, :aliases => "-p",
         :desc => "running on daemon mode?"

  def start
    puts "start #{options.inspect}"
  end

  desc "stop" ,"stop server"
  option :delay,  :default => 0, :aliases => "-w",
         :desc => "wait server finish it's job"
  def stop
    puts "stop"
  end


end

ThorExample.start